module.exports = {
    Cache: require('./cache/keyv_singleton'),
    sendEmail: require('./Senders/email_sender'),
    smsService: require('./Senders/sms_sender'),
    RestPwdReq: require('./security/resetPwdReq.service'),
    RestPwd: require('./security/resetPwd.service'),
    Register: require('./security/register.service'),
    tokenBaseActivation: require('./security/tokenBaseActivation.service'),
    SignIn: require('./security/login.service'),
    TokenRefresh: require('./security/tokenRefresh.service'),
    changePassword: require('./security/changePassword.service'),
    gen_qrcode: require('./qrcodes/gen_qrcode'),
    verifyOtp: require('./security/verifyOtp.service'),
    Otp: require('./security/otp.service'),
    MobileRegister: require('./security/mobileRegister.service'),
    driverSSE: require('./sse/driver_sse_publisher'),
}